name: sentinel-etl
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.13.2
  - geos=3.11.1
  - geotiff=1.7.1
  - httpx=0.24.1
  - numpy=1.25.0
  - pandas=2.0.3
  - pillow=9.4.0
  - pip=23.1.2
  - python=3.11.4
  - requests=2.29.0
  - seaborn=0.12.2
  - scikit-image=0.21.0
  - setuptools=67.8.0
  - shapely=2.0.1
  - rasterio==1.3.6
  - pip:
      - contextily==1.3.0
      - geojson==3.0.1
      - hydra-core==1.3.2
      - ohsome==0.2.0
      - omegaconf==2.3.0
      - tifffile==2023.9.26
      - tqdm==4.66.1
      - geocube==0.4.2
      - sentinelhub==3.9.1
      - aiofiles==23.2.1
